//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoCyteSimulator.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpDoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpDoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NovoCyteSimulator.Res.ExpDoc", typeof(ExpDoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sample events..
        /// </summary>
        internal static string AddSampleData {
            get {
                return ResourceManager.GetString("AddSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data were deleted, free unused file space now?.
        /// </summary>
        internal static string AskCompactFile {
            get {
                return ResourceManager.GetString("AskCompactFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking experiment file integrity....
        /// </summary>
        internal static string CheckingFileIntegrity {
            get {
                return ResourceManager.GetString("CheckingFileIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find FCPlate.sys file..
        /// </summary>
        internal static string CouldNotFindFCPlate {
            get {
                return ResourceManager.GetString("CouldNotFindFCPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sample..
        /// </summary>
        internal static string CreateSample {
            get {
                return ResourceManager.GetString("CreateSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sample..
        /// </summary>
        internal static string DeleteSample {
            get {
                return ResourceManager.GetString("DeleteSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sample events..
        /// </summary>
        internal static string DeleteSampleData {
            get {
                return ResourceManager.GetString("DeleteSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of sample {0} is damaged..
        /// </summary>
        internal static string EventsDataBroken {
            get {
                return ResourceManager.GetString("EventsDataBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is invalid or damaged..
        /// </summary>
        internal static string FileDamage {
            get {
                return ResourceManager.GetString("FileDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is damaged because of system crash or power failure while saving data to disk. Experiment cannot be resumed and file will be opened in read-only mode..
        /// </summary>
        internal static string FileIntegrityCheckFailed {
            get {
                return ResourceManager.GetString("FileIntegrityCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file may have been opened already.
        ///It will be opened in read only mode..
        /// </summary>
        internal static string FileOpendAlready {
            get {
                return ResourceManager.GetString("FileOpendAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is opened from {0}.
        ///It is read only and cannot be resumed..
        /// </summary>
        internal static string FileOpenFromCD {
            get {
                return ResourceManager.GetString("FileOpenFromCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is damaged, only parts of its data have been loaded..
        /// </summary>
        internal static string FilePartiallyDamage {
            get {
                return ResourceManager.GetString("FilePartiallyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is read only.
        ///It cannot be resumed..
        /// </summary>
        internal static string FileReadOnly {
            get {
                return ResourceManager.GetString("FileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is generated or modified by a newer version of {0} software and cannot be opened. Please upgrade {1} to the latest version and try again..
        /// </summary>
        internal static string GeneratedByNewerSWVersion {
            get {
                return ResourceManager.GetString("GeneratedByNewerSWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import sample events..
        /// </summary>
        internal static string ImportSampleData {
            get {
                return ResourceManager.GetString("ImportSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data from experiment file {1} failed. Please check if experiment file {1} exist at the designated directory..
        /// </summary>
        internal static string LoadEventsFailed {
            get {
                return ResourceManager.GetString("LoadEventsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is generated or modified by a newer version of {0} software. It will be opened in read-only mode..
        /// </summary>
        internal static string ModifySWVersionLarger {
            get {
                return ResourceManager.GetString("ModifySWVersionLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite sample events..
        /// </summary>
        internal static string OverWriteSampleData {
            get {
                return ResourceManager.GetString("OverWriteSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file failed.
        ///The file {0} might have been opened..
        /// </summary>
        internal static string SaveAsFileOpened {
            get {
                return ResourceManager.GetString("SaveAsFileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file {0}.
        ///Save file failed..
        /// </summary>
        internal static string SaveFailedCouldNotFindFile {
            get {
                return ResourceManager.GetString("SaveFailedCouldNotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file failed..
        /// </summary>
        internal static string SaveFileFailed {
            get {
                return ResourceManager.GetString("SaveFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters of some uncollected samples are incompatible with current instrument configuration and will be changed accordingly..
        /// </summary>
        internal static string StrParameterNotCompactible {
            get {
                return ResourceManager.GetString("StrParameterNotCompactible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update sample analysis..
        /// </summary>
        internal static string UpdateSampleAnalysis {
            get {
                return ResourceManager.GetString("UpdateSampleAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update sample settings..
        /// </summary>
        internal static string UpdateSampleSettings {
            get {
                return ResourceManager.GetString("UpdateSampleSettings", resourceCulture);
            }
        }
    }
}
